shell = "/usr/bin/fish"

import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
size = 15.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.94
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 109
lines = 28

[window.position]
x = 167
y = 123

